/**
 * Property-Based Test for Bug 4 fix — `TablaKardex` refleja el prop `data` actualizado
 *
 * Feature: kardex-infinite-loading-fix
 * Property 4: `TablaKardex` refleja el prop `data` actualizado
 * Validates: Requirements 2.4
 *
 * For any non-empty array of kardex records generated by fast-check,
 * rendering <TablaKardex data={records} .../> must produce exactly
 * records.length rows in the <tbody>.
 */
import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { render, cleanup } from '@testing-library/react';
import * as fc from 'fast-check';
import { TablaKardex } from '../components/organismos/Tablas/TablaKardex';

// --- Mock: useKardexStore ---
vi.mock('../store/KardexStore', () => ({
  useKardexStore: vi.fn(() => ({
    eliminarKardex: vi.fn(),
  })),
}));

// --- Mock: sweetalert2 ---
vi.mock('sweetalert2', () => ({
  default: {
    fire: vi.fn(() => Promise.resolve({ isConfirmed: false })),
  },
}));

// --- Mock: Paginacion — renders nothing to keep test focused ---
vi.mock('../components/organismos/Tablas/Paginacion', () => ({
  Paginacion: () => <div data-testid="paginacion" />,
}));

// --- Mock: ContentAccionesTabla ---
vi.mock('../components/organismos/ContentAccionesTabla', () => ({
  ContentAccionesTabla: () => <div data-testid="acciones-tabla" />,
}));

// --- Mock: react-icons/fa ---
vi.mock('react-icons/fa', () => ({
  FaArrowsAltV: () => <span data-testid="sort-icon" />,
}));

// --- Mock: styles/variables ---
vi.mock('../styles/variables', () => ({
  variable: {
    bpbart: '768px',
    bphomer: '1200px',
    bpmarge: '992px',
    bplisa: '576px',
    iconoflechaderecha: () => null,
    iconotodos: () => null,
    iconoconfiguracion: null,
    iconocorreo: null,
  },
}));

// --- Mock: styles/breackpoints ---
vi.mock('../styles/breackpoints', () => ({
  Device: {
    tablet: '(min-width: 768px)',
    mobile: '(min-width: 576px)',
  },
}));

// --- Mock: react-router-dom ---
vi.mock('react-router-dom', () => ({
  useNavigate: () => vi.fn(),
}));

// ---------------------------------------------------------------------------
// Arbitrary: generates a valid kardex record object
// ---------------------------------------------------------------------------
const kardexRecordArbitrary = fc.record({
  descripcion: fc.string({ minLength: 1, maxLength: 50 }),
  fecha: fc.date({ min: new Date('2020-01-01'), max: new Date('2025-12-31') }).map(
    (d) => d.toISOString().split('T')[0]
  ),
  tipo: fc.constantFrom('entrada', 'salida'),
  detalle: fc.string({ minLength: 0, maxLength: 100 }),
  nombres: fc.string({ minLength: 1, maxLength: 50 }),
  cantidad: fc.integer({ min: 1, max: 1000 }),
  stock: fc.integer({ min: 0, max: 10000 }),
});

const defaultProps = {
  SetopenRegistro: vi.fn(),
  setdataSelect: vi.fn(),
  setAccion: vi.fn(),
};

afterEach(() => {
  cleanup();
});

beforeEach(() => {
  vi.clearAllMocks();
});

describe('TablaKardex Bug 4 PBT — Property 4: TablaKardex refleja el prop data actualizado', () => {
  /**
   * Property 4: For any non-empty array of kardex records (up to pageSize=10),
   * <TablaKardex data={records} .../> renders exactly records.length rows in tbody.
   *
   * Note: TablaKardex uses getPaginationRowModel() which defaults to 10 rows per page.
   * Arrays are capped at 10 so all records fit on the first page, allowing us to
   * assert rows === records.length directly without pagination interaction.
   *
   * Validates: Requirements 2.4
   */
  it('PBT: para cualquier array no vacío de registros kardex (≤ pageSize), tbody tiene exactamente records.length filas', () => {
    fc.assert(
      fc.property(
        fc.array(kardexRecordArbitrary, { minLength: 1, maxLength: 10 }),
        (records) => {
          const { container } = render(
            <TablaKardex data={records} {...defaultProps} />
          );

          const tbody = container.querySelector('tbody');
          expect(tbody).not.toBeNull();

          const rows = tbody.querySelectorAll('tr');
          expect(rows).toHaveLength(records.length);

          cleanup();
        }
      ),
      { numRuns: 50 }
    );
  });

  it('PBT: para un único registro kardex, tbody tiene exactamente 1 fila', () => {
    fc.assert(
      fc.property(kardexRecordArbitrary, (record) => {
        const { container } = render(
          <TablaKardex data={[record]} {...defaultProps} />
        );

        const tbody = container.querySelector('tbody');
        expect(tbody).not.toBeNull();

        const rows = tbody.querySelectorAll('tr');
        expect(rows).toHaveLength(1);

        cleanup();
      }),
      { numRuns: 30 }
    );
  });
});
